[package]
name = "yew-router-example"
version = "0.1.0"
authors = ["Alexis Luengas <al096@hdm-stuttgart.de>"]

[dependencies]
log = "0.4"
serde = "1.0.82"
serde_derive = "1.0.82"
stdweb = "0.4.12"
yew = { git = "https://github.com/DenisKolodin/yew" }