[package]
name = "wasm-spa"
version = "0.1.0"
authors = ["Alexis Luengas <al096@hdm-stuttgart.de>"]

[dependencies]
root = { path = "../root" }
log = "0.4"
web_logger = "0.1"
yew = { git = "https://github.com/DenisKolodin/yew", rev = "49319b8c02a8eeb15ed4c8a8761f83adcee856b0" }
