[workspace]
members = [
    "app",
    "common",
    "header",
    "header-input",
    "identifiers",
    "root",
    "tweets",
    "util",
    "wire",
]
exclude = [
    "yew_patterns"
]

[profile.dev]
opt-level = 1
debug = true

[profile.release]
# opt-level = 3
debug = true